/* TABLAS REALIZADAS POR BELÉN CANDELAS SÁNCHEZ-CARNERERO */

/* TABLA USUARIO */
CREATE TABLE Usuario(
  ID INT PRIMARY KEY,
  Nombre VARCHAR(100) NOT NULL,
  Correo VARCHAR(100) NOT NULL UNIQUE,
  Contraseña VARCHAR(255) NOT NULL
);

/* TABLA ORGANIZADOR */
CREATE TABLE Organizador(
  ID INT PRIMARY KEY,
  Nombre VARCHAR(100) NOT NULL,
  Contacto VARCHAR(100) NOT NULL UNIQUE
);

/* TABLA CATEGORÍA */
CREATE TABLE Categoria(
  ID INT PRIMARY KEY,
  Nombre VARCHAR(100) NOT NULL UNIQUE
);

/* TABLA UBICACIÓN */
CREATE TABLE Ubicacion(
  ID INT PRIMARY KEY,
  Tipo VARCHAR(50) NOT NULL CHECK (Tipo IN ('Presencial', 'Online')),
  Direccion VARCHAR(255)
);

/* TABLA EVENTO */
CREATE TABLE Evento(
  ID INT PRIMARY KEY,
  Nombre VARCHAR(150) NOT NULL,
  Fecha DATE NOT NULL,
  Duracion INT NOT NULL,
  Ubicacion_ID INT NOT NULL,
  Categoria_ID INT NOT NULL,
  Organizador_ID INT NOT NULL,
  FOREIGN KEY (Ubicacion_ID) REFERENCES Ubicacion(ID),
  FOREIGN KEY (Categoria_ID) REFERENCES Categoria(ID),
  FOREIGN KEY (Organizador_ID) REFERENCES Organizador(ID)
);

/* TABLA INSCRIPCIÓN */
CREATE TABLE Inscripcion(
  ID INT PRIMARY KEY,
  Usuario_ID INT NOT NULL,
  Evento_ID INT NOT NULL,
  Fecha_Registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Usuario_ID) REFERENCES Usuario(ID),
  FOREIGN KEY (Evento_ID) REFERENCES Evento(ID),
  UNIQUE (Usuario_ID, Evento_ID)
);


/* TABLAS REALIZADAS POR BELÉN CANDELAS SÁNCHEZ-CARNERERO */